buildscript {
    repositories {
        mavenCentral()
        gradlePluginPortal()
    }

    dependencies {
        classpath 'com.palantir.gradle.externalpublish:gradle-external-publish-plugin:1.33.0'
        classpath 'com.palantir.gradle.failure-reports:gradle-failure-reports:1.18.0'
        classpath 'com.palantir.gradle.gitversion:gradle-git-version:4.3.0'
        classpath 'com.palantir.gradle.idea-configuration:gradle-idea-configuration:0.8.0'
        classpath 'com.palantir.gradle.jdks:gradle-jdks:0.74.0'
        classpath 'com.palantir.gradle.jdkslatest:gradle-jdks-latest:0.26.0'
    }
}

apply plugin: 'com.palantir.external-publish-custom'
apply plugin: 'com.palantir.failure-reports'
apply plugin: 'com.palantir.git-version'
apply plugin: 'com.palantir.jdks'
apply plugin: 'com.palantir.jdks.latest'

group 'com.palantir.launching'

version ((System.env.CIRCLE_TAG ?: gitVersion()).replaceAll('^v', ''))

externalPublishing {
    publication('goJavaLauncher') {
        artifactId 'go-java-launcher'
        artifact file("out/dist/go-java-launcher/${project.version}/bin/go-java-launcher-${project.version}.tgz")
    }
    publication('goInit') {
        artifactId 'go-init'
        artifact file("out/dist/go-init/${project.version}/bin/go-init-${project.version}.tgz")
    }
}

jdks {
    daemonTarget = 21
}
