products:
  go-init:
    build:
      main-pkg: ./init/main
      os-archs:
      - os: darwin
        arch: amd64
      - os: linux
        arch: amd64
    dist:
      disters:
        bin:
          type: bin
          script: |
            #!/bin/bash
            set -euo pipefail
            mkdir $DIST_WORK_DIR/service
            mv $DIST_WORK_DIR/bin $DIST_WORK_DIR/service/bin
    publish: {}
  go-java-launcher:
    build:
      main-pkg: ./launcher/main
      os-archs:
      - os: darwin
        arch: amd64
      - os: linux
        arch: amd64
    dist:
      disters:
        bin:
          type: bin
          script: |
            #!/bin/bash
            set -euo pipefail
            mkdir $DIST_WORK_DIR/service
            mv $DIST_WORK_DIR/bin $DIST_WORK_DIR/service/bin
    publish: {}
product-defaults:
  publish:
    group-id: com.palantir.launching
